---
title: "Test.Rmd"
author: "Alexander Martinez"
date: "6/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#PART 1 TIDYING UP THE CURRENT FREE AGENTS


```{r Scraping the Data}
#retrieve appropriate packages
library(rvest)
library(stringr)
library(tidyverse)
library(stringi)

#read in the data by scraping it from spotrac.com

faurl <- "https://www.spotrac.com/nba/free-agents/"
webpage <- read_html(faurl)
fatable <- html_nodes(webpage,"table")
fa <- html_table(fatable, fill = T, header = T)[[1]]

#transform into a data frame
fa_df <- as.data.frame(fa)
dim(fa_df)

#Erase the first word of a column; oddly enough, it was separated by 4 spaces.
fa_df$`Player (189)` <- word(fa_df$`Player (189)`, 2, sep = "    ")
head(fa_df)

# rename the player column
fa_df <- fa_df %>%
  rename(Player = `Player (189)`)

```





Now I need to scrape average stats from another website and match the free agent names to those stats
```{r Cleaning the Data}
# Find css selector
css_selector <- "#div_per_game_stats"
statpage <- "https://www.basketball-reference.com/leagues/NBA_2022_per_game.html"

#use pipelines to get the tables
nba_stats <- statpage %>%
  read_html()%>%
  html_element(css = css_selector) %>%
  html_table()
# remove rank column
nba_stats <- nba_stats %>%
  select(-Rk)
# every column is character, which is not correct
sapply(nba_stats,class)
# make an object with all of the numeric columns
cols.num <- names(nba_stats[,c(3,5:29)])
# convert all into numeric
nba_stats[cols.num] <- sapply(nba_stats[cols.num], as.numeric)


tail(nba_stats)
# some of the names do not match exactly, we must go in and manually input them, we can check which names like so
fa_df %>% select(Player) %>% anti_join(nba_stats)

# Using recode to change all of the names that do not match
fa_df <- fa_df %>%
  mutate(Player = recode(Player, "Bruce Brown Jr." = "Bruce Brown",
                         "Patrick Mills" = "Patty Mills",
                         "Mohamed Bamba" = "Mo Bamba",
                         "Louis Williams" = "Lou Williams",
                         "Sviatoslav Mykhailiuk" = "Svi Mykhailiuk",
                         "Jae’Sean Tate" = "Jae'Sean Tate",
                         "Nicolas Claxton" = "Nic Claxton",
                         "Danuel House" = "Danuel House Jr.",
                         "Ishmail Wainright" = "Ish Wainright",
                         "R.J. Nembhard" = "RJ Nembhard Jr.",
                         "Lindell Wiggington" = "Lindell Wigginton",
                         "Dennis Schröder" = "Dennis Schroder"
                         ))
# imputing the average career stats for DNP's
#T.J. Warren
nba_stats[nrow(nba_stats) + 1,] <- list("T.J. Warren","SF",28,"IND" , NA, NA, NA, 6.4,12.6,.507,.7,2.1,.357,5.7,10.5,.536,.536,1.9,2.5,.78,1.4,2.8,4.1,1.2,1.0,.5,1.0,2.4,15.5)
#John Wall
nba_stats[nrow(nba_stats) + 1,] <- list("John Wall","PG",31,"HOU", NA, NA, NA, 6.9, 16, .431, 1.0, 3.1, .323, 5.9, 12.9,.457,.462,4.3,5.5,.779,.6,3.7,4.3,9.1,1.7,.7,3.8,2.2,19.1)
#Kendrick Nunn
nba_stats[nrow(nba_stats) + 1,] <- list("Kendrick Nunn","PG",26,"LAL", NA, NA, NA, 5.9, 12.8, .458, 2.1, 5.8, .364, 3.7, 7,.535,.540,1.1,1.3,.881,.3,2.6,2.9,3.0,.9,.2,1.6,2.1,15.0)


# Now we want to deal with all the names with an accent
nba_stats$Player <- stri_trans_general(str = nba_stats$Player,
                                   id = "Latin-ASCII")

# merge the tables based on player name
new_df <- merge(fa_df, nba_stats, by = "Player")
dim(new_df)
head(new_df)


```





We finalize cleaning our tidy table by getting rid of the redundancy.
```{r Extract the Duplicate Rows}
# clean up the table 


# there are players that were on multiple teams last season, and "tot" represents total
# this gets all of the distinct players' names that have the "TOT" 
tot <- new_df %>%
  filter(Tm == "TOT") %>%
  select(Player)%>%
  distinct()

# Use the %in% operator to extract the rows of the data frame with those players' names
# use that to create a data frame that extracts the rows of within those group of players that we do not want
df <- new_df[new_df$Player %in% tot$Player,] %>%
  filter(Tm != "TOT")
head(df)

# antijoin with the rows we do not want, this takes those rows out
df2 <- new_df %>% anti_join(df)
dim(df2)


```


#PART 2: TIDYING UP THE PAST FREE AGENTS
```{r PAST FREE AGENTS 2016 - 2021}
# this a loop done that grabs all of the tables across multiple pages and combines them into one table. It then merges them with 
years <- c(2016:2021)
column_names <- c("Rk","Player","Pos","Age","Type","OTm","2020-21 Stats","WS","NTm","Terms","Notes")
final_table <- {}
for(i in 1:length(years)){
  
url <- paste0("https://www.basketball-reference.com/friv/free_agents.cgi?year=",years[i])
  
  past_free_agency_page <- read_html(url)
  
  past_free_agency_webtable<- html_nodes(past_free_agency_page, "table")
  
  past_free_agency_table <- html_table(past_free_agency_webtable, header = T)[[1]]
  
  final_table <- rbind(past_free_agency_table, final_table)
}


```

